services:
  db:
    image: postgres:12
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - .:/src
    environment:
      - DATABASE_URL=postgres://Madara2:111@postgres_db:5432/Kitten_shows
      - SECRET_KEY=${SECRET_KEY}

volumes:
  postgres_data:
